"""Initial migration

Revision ID: 71244459c239
Revises: 
Create Date: 2025-08-07 23:41:15.484474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71244459c239'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('channel_handle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('custom_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'INACTIVE', name='channelstatus'), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('check_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_video_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_process', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_last_checked', 'channels', ['last_checked_at'], unique=False)
    op.create_index('idx_channel_status_priority', 'channels', ['status', 'priority_level'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_status'), 'channels', ['status'], unique=False)
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=True)
    op.create_table('processing_sessions',
    sa.Column('session_type', sa.Enum('BULK_PROCESSING', 'CHANNEL_SYNC', 'SCHEDULED', 'MANUAL', 'RECOVERY', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('INITIALIZED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('failed_jobs', sa.Integer(), nullable=False),
    sa.Column('cancelled_jobs', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('estimated_completion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_resumable', sa.Boolean(), nullable=False),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checkpoint_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_started', 'processing_sessions', ['started_at'], unique=False)
    op.create_index('idx_session_status', 'processing_sessions', ['status'], unique=False)
    op.create_index('idx_session_type_status', 'processing_sessions', ['session_type', 'status'], unique=False)
    op.create_index(op.f('ix_processing_sessions_id'), 'processing_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_processing_sessions_session_type'), 'processing_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_processing_sessions_status'), 'processing_sessions', ['status'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.Enum('CHANNEL_DISCOVERY', 'VIDEO_DISCOVERY', 'TRANSCRIPT_EXTRACTION', 'VALUABLE_DETECTION', 'IDEA_EXTRACTION', 'BULK_PROCESSING', 'CLEANUP', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='jobpriority'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_entity', 'processing_jobs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_job_scheduled', 'processing_jobs', ['scheduled_at', 'status'], unique=False)
    op.create_index('idx_job_session', 'processing_jobs', ['session_id'], unique=False)
    op.create_index('idx_job_status_priority', 'processing_jobs', ['status', 'priority'], unique=False)
    op.create_index('idx_job_type_status', 'processing_jobs', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_entity_id'), 'processing_jobs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_entity_type'), 'processing_jobs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_priority'), 'processing_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_processing_jobs_session_id'), 'processing_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('videos',
    sa.Column('youtube_video_id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', name='videostatus'), nullable=False),
    sa.Column('is_valuable', sa.Boolean(), nullable=True),
    sa.Column('valuable_score', sa.Float(), nullable=True),
    sa.Column('valuable_reason', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_captions', sa.Boolean(), nullable=False),
    sa.Column('caption_languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_channel_status', 'videos', ['channel_id', 'status'], unique=False)
    op.create_index('idx_video_published', 'videos', ['published_at'], unique=False)
    op.create_index('idx_video_status_discovered', 'videos', ['status', 'discovered_at'], unique=False)
    op.create_index('idx_video_valuable', 'videos', ['is_valuable', 'valuable_score'], unique=False)
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('YOUTUBE_AUTO', 'YOUTUBE_MANUAL', 'WHISPER', 'CUSTOM', name='transcriptsource'), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ES', 'FR', 'DE', 'PT', 'IT', 'JA', 'KO', 'ZH', 'OTHER', name='transcriptlanguage'), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('transcript_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_content', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_language', 'transcripts', ['language', 'language_code'], unique=False)
    op.create_index('idx_transcript_video_source', 'transcripts', ['video_id', 'source'], unique=False)
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_source'), 'transcripts', ['source'], unique=False)
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_source'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_index('idx_transcript_video_source', table_name='transcripts')
    op.drop_index('idx_transcript_language', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_index('idx_video_valuable', table_name='videos')
    op.drop_index('idx_video_status_discovered', table_name='videos')
    op.drop_index('idx_video_published', table_name='videos')
    op.drop_index('idx_video_channel_status', table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_session_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_priority'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_entity_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_entity_id'), table_name='processing_jobs')
    op.drop_index('idx_job_type_status', table_name='processing_jobs')
    op.drop_index('idx_job_status_priority', table_name='processing_jobs')
    op.drop_index('idx_job_session', table_name='processing_jobs')
    op.drop_index('idx_job_scheduled', table_name='processing_jobs')
    op.drop_index('idx_job_entity', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_processing_sessions_status'), table_name='processing_sessions')
    op.drop_index(op.f('ix_processing_sessions_session_type'), table_name='processing_sessions')
    op.drop_index(op.f('ix_processing_sessions_id'), table_name='processing_sessions')
    op.drop_index('idx_session_type_status', table_name='processing_sessions')
    op.drop_index('idx_session_status', table_name='processing_sessions')
    op.drop_index('idx_session_started', table_name='processing_sessions')
    op.drop_table('processing_sessions')
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_status'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index('idx_channel_status_priority', table_name='channels')
    op.drop_index('idx_channel_last_checked', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
