"""Add User table for authentication

Revision ID: f91834886dd0
Revises: 71244459c239
Create Date: 2025-08-10 22:35:31.041823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91834886dd0'
down_revision: Union[str, Sequence[str], None] = '71244459c239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Unique username'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', name='userrole'), nullable=False, comment='User role for authorization'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', name='userstatus'), nullable=False, comment='Account status'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether email is verified'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser flag for system administration'),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='When email was verified'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Last activity timestamp'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Last password change timestamp'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='User avatar URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='User biography/description'),
    sa.Column('preferences', sa.Text(), nullable=True, comment='User preferences in JSON format'),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, comment='Whether 2FA is enabled'),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True, comment='2FA secret key (encrypted)'),
    sa.Column('recovery_codes', sa.Text(), nullable=True, comment='2FA recovery codes (encrypted)'),
    sa.Column('login_attempts', sa.Integer(), nullable=False, comment='Failed login attempts counter'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API key for programmatic access'),
    sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True, comment='When API key was created'),
    sa.Column('registration_ip', sa.String(length=45), nullable=True, comment='IP address used for registration'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='IP address of last login'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Last user agent string'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_password', 'users', ['email', 'hashed_password'], unique=False)
    op.create_index('idx_users_last_login', 'users', ['last_login_at'], unique=False)
    op.create_index('idx_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('idx_users_status_active', 'users', ['status', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_index('idx_users_status_active', table_name='users')
    op.drop_index('idx_users_role_active', table_name='users')
    op.drop_index('idx_users_last_login', table_name='users')
    op.drop_index('idx_users_email_password', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
